
crypto_encode_decode_encoders_src = files(
    'encoder_meth.c',
    'encoder_lib.c',
    'encoder_pkey.c',
    'encoder_err.c')

crypto_encode_decode_decoders_src = files(
    'decoder_meth.c',
    'decoder_lib.c',
    'decoder_pkey.c',
    'decoder_err.c')

crypto_src += [
    crypto_encode_decode_encoders_src,
    crypto_encode_decode_decoders_src]
